forum-app/app/urls.py
from django.urls import path
from . import views  # from current folder


urlpatterns = [
    path('', views.index, name="index"),

    # path('add_user', views.add_user, name="add_user"),
    # path('<int:user_id>/', views.user_detail, name="user_detail"),
    path('add_post', views.add_post, name="add_post"),

    path('<int:post_id>/', views.post_detail, name="post_detail"),
    path('<int:post_id>/add_comment', views.add_comment, name="add_comment"),
]

forum-app/forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('app.urls', 'forum'), namespace="forum")),
]

forum-app/app/models.py
from django.db import models


class User(models.Model):
    id = models.IntegerField(primary_key=True, null=False, db_index=True)
    email = models.EmailField(null=False, unique=True)
    password = models.CharField(null=False, max_length=100)
    created_at = models.DateTimeField(auto_now=True, null=False)


class Post(models.Model):
    id = models.IntegerField(primary_key=True, null=False, db_index=True)
    title = models.CharField(null=False, max_length=100)
    content = models.CharField(null=False, max_length=300)
    published = models.BooleanField(default=True, null=False)
    created_at = models.DateTimeField(auto_now=True, null=False)
    owner_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False)


class Vote(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False, unique=True)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, null=False, unique=True)

    class Meta:
        unique_together = (('user_id', 'post_id'),)


class Comment(models.Model):
    id = models.IntegerField(primary_key=True, null=False, db_index=True)
    content = models.CharField(null=False, max_length=300)
    created_at = models.DateTimeField(auto_now=True, null=False)
    owner_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    main_post_id = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)

forum-app/app/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Comment, User
from django.utils import timezone


def index(request):
    latest_posts = Post.objects.order_by('created_at')[:5]
    context = {'latest_posts': latest_posts}
    return render(request, 'forum/index.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {"post": post}
    return render(request, 'forum/detail.html', context)


def add_post(request):
    try:
        title = request.POST['title']
        context = request.POST['content']
        post = Post(title=title, content=context, created_at=timezone.now())
        post.save()
    except:
        return render(request, 'forum/index.html')

    return HttpResponseRedirect(reverse('forum:index'))


def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    owner_id = get_object_or_404(User, pk=post.owner_id)
    try:
        comment = request.POST['comment']
        post.comment_set.create(content=comment, created_at=timezone.now(), owner_id=owner_id)
        post.save()
    except:
        return render(request, 'forum/detail.html', {'post': post, 'error_message': 'Please enter some text'})

    return HttpResponseRedirect(reverse('forum:detail', args=(post.id,)))

forum-app/app/templates/forum/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forum</title>
    <link rel="stylesheet" type="text/css" href="{% static 'forum/style.css' %}" />
</head>
<body>
    {% block main_content %}
    {% endblock %}
</body>
</html>

forum-app/app/templates/forum/detail.html
{% extends 'forum/base.html' %}
{% block main_content %}
<h1>{{post.title}}</h1>
<p>{{post.content}}</p>
{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}
<h4>Comments</h4>
{% csrf_token %}
{% for comment in post.comment_set.all %}
    <li><b>{{comment.content}}</b></li>
{% endfor %}
    <form action="{% url 'forum:add_comment' post.id %}" method="post">
        {% csrf_token %}

        <textarea id="comment" name="comment" rows="2" cols="30" placeholder="Enter your comment here..."></textarea>
        <input type="submit" value="Add" />
    </form>

{% endblock %}

forum-app/app/templates/forum/index.html
{% extends 'forum/base.html' %}
{% block main_content %}
    {% if latest_posts %}
    <ul>
        {% for post in latest_posts %}
        <li><a href={% url "forum:post_detail" post.id %}><b>{{post.title}}</b></a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No posts yet. Please add a new one.</p>

    {% endif %}
        <form action="{% url 'forum:add_post' %}" method="post">
            {% csrf_token %}
            <label for="title">Post Title</label>
            <input type="text" id="title" name="title" placeholder="Enter your title here..." required><br>
            <label for="content">Post Details</label>
            <textarea id="content" name="content" rows="1" cols="30" placeholder="Enter your details here..." required></textarea><br>
            <input type="submit" value="Add" />
        </form>
{% endblock %}